name: weather
description: Single page weather app with multiple locations

publish_to: 'none'
version: 0.0.1+5

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  _di_layer:
    path: ./packages/_di_layer
  _presentation_layer:
    path: ./packages/_presentation_layer
    
  flutter:
    sdk: flutter
    
  flutter_native_splash: ^2.1.6
  flutter_riverpod: ^2.0.0-dev.7
  google_mobile_ads: ^1.2.0
  logging: ^1.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^2.0.1
  
  flutter_test:
    sdk: flutter

  icons_launcher: ^1.1.7
        
flutter:
  uses-material-design: true

flutter_icons:
  # android: true
  ios: true
  image_path: "assets/icon/app_launcher_icon.png"
