name: weather_colors
description: Current weather and forecast with colors 

publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '^3.7.0'
  flutter: ">=3.22.2"

dependencies:
  bitsdojo_window: ^0.1.6
  country_picker: # ^2.0.15-dev.1
    git:
      url: https://github.com/cc-nogueira/flutter_country_picker.git
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.0
  freezed_annotation: ^2.4.4
  google_mobile_ads: ^6.0.0
  hooks_riverpod: ^2.6.1
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latinize: ^0.1.0-nullsafety.0
  logging: ^1.3.0
  meta: ^1.16.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  path_provider: ^2.1.5
  qty: ^0.9.2
  quiver: ^3.2.2
  riverpod_annotation: ^2.6.1
  syncfusion_flutter_charts: ^29.2.10
  syncfusion_localizations: ^29.2.10
  tuple: ^2.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  icons_launcher: ^3.0.1
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  objectbox_generator: ^4.3.0
  riverpod_generator: ^2.6.3
        
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Alice
      fonts:
        - asset: fonts/Alice-Regular.ttf
  assets:
    - assets/image/open_weather_logo.png
    - assets/image/syncfusion_logo_150dpi.png
    - assets/image/wind_direction_black.png
    - assets/image/wind_direction_white.png
    - assets/weather/
