name: weather_colors
description: Current weather and forecast with colors 

publish_to: 'none'
version: 0.0.7+25

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  
  _di_layer:
    path: ./packages/_di_layer
  _presentation_layer:
    path: ./packages/_presentation_layer
    
  bitsdojo_window: 0.1.2

  flutter:
    sdk: flutter
    
  flutter_native_splash: ^2.2.2
  flutter_riverpod: ^2.0.0-dev.9
  google_mobile_ads: ^1.2.0
  logging: ^1.0.2


dev_dependencies:
  flutter_lints: ^2.0.1
  
  flutter_test:
    sdk: flutter

  icons_launcher: ^1.1.9
        
flutter:
  uses-material-design: true

flutter_icons:
  # android: true
  ios: true
  image_path: "assets/icon/app_launcher_icon.png"
