name: weather_colors
description: Current weather and forecast with colors 

publish_to: 'none'
version: 0.2.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bitsdojo_window: ^0.1.5
  country_picker: # ^2.0.15-dev.1
    git:
      url: https://github.com/cc-nogueira/flutter_country_picker.git
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.1.3
  flutter_slidable: ^2.0.0
  freezed_annotation: ^2.2.0
  google_mobile_ads: ^2.3.0
  hooks_riverpod: ^2.1.3
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.8.0
  latinize: ^0.1.0-nullsafety.0
  logging: ^1.1.1
  meta: ^1.8.0
  objectbox: ^1.7.2
  objectbox_flutter_libs: ^1.7.2
  path_provider: ^2.0.12
  qty: ^0.9.2
  quiver: ^3.2.1
  riverpod_annotation: ^1.1.1
  syncfusion_flutter_charts: ^20.4.48
  syncfusion_localizations: ^20.4.48
  tuple: ^2.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  icons_launcher: ^2.0.6
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  objectbox_generator: ^1.7.2
  riverpod_generator: ^1.1.1
        
flutter:
  uses-material-design: true
  fonts:
    - family: Alice
      fonts:
        - asset: fonts/Alice-Regular.ttf
  assets:
    - assets/image/open_weather_logo.png
    - assets/image/syncfusion_logo_150dpi.png
    - assets/image/wind_direction_black.png
    - assets/image/wind_direction_white.png
    - assets/weather/

flutter_icons:
  # android: true
  ios: true
  image_path: "assets/icon/app_launcher_icon.png"
