name: weather
description: Single page weather app with multiple locations

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  _di_layer:
    path: ./packages/_di_layer
  _presentation_layer:
    path: ./packages/_presentation_layer
    
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
        
flutter:
  uses-material-design: true
