name: _domain_layer
description: Domain Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
    
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  logging: ^1.0.2
  qty: ^0.9.1
  quiver: ^3.0.1+1
  riverpod: ^2.0.0-dev.5
  tuple: ^2.0.0
  
dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  mockito: ^5.1.0

flutter:
