name: _domain_layer
description: Domain Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
    
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  meta: ^1.8.0
  qty: ^0.9.2
  quiver: ^3.2.1
  riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  tuple: ^2.0.1
  
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  riverpod_generator: ^1.1.1

flutter:
