name: _domain_layer
description: Domain Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
    
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  logging: ^1.0.2
  meta: ^1.7.0
  qty: ^0.9.2
  quiver: ^3.1.0
  riverpod: ^2.0.0-dev.7
  tuple: ^2.0.0
  
dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mockito: ^5.1.0

flutter:
