name: _data_layer
description: Data Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer
    
  flutter:
    sdk: flutter
  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1
  path_provider: ^2.0.9
  riverpod: any

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^1.4.1
      
flutter:
