name: _di_layer
description: DI Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _data_layer:
    path: ../_data_layer
  _domain_layer:
    path: ../_domain_layer
  _presentation_layer:
    path: ../_presentation_layer
  _service_layer:
    path: ../_service_layer
    
  flutter:
    sdk: flutter
  meta: ^1.8.0
  riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^1.1.1
    
flutter:
