name: _presentation_layer
description: Presentation Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer
    
  country_picker: ^2.0.12
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_slidable: ^1.2.0
  hooks_riverpod: ^1.0.3

  qty: ^0.6.0
  #   path: ../../../../../dart/qty

#  qty: any
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
