name: _presentation_layer
description: Presentation Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer

  bitsdojo_window: ^0.1.5
  country_picker: # ^2.0.15-dev.1
    git:
      url: https://github.com/cc-nogueira/flutter_country_picker.git

  faker: ^2.0.0

  flutter:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1
  flutter_hooks: ^0.18.5+1

  flutter_localizations:
    sdk: flutter

  flutter_slidable: ^2.0.0
  google_mobile_ads: ^2.3.0
  hooks_riverpod: ^2.1.1

  intl: ^0.17.0
  latinize: ^0.1.0-nullsafety.0
  logging: ^1.1.0
  meta: ^1.8.0
  qty: ^0.9.2
  riverpod_annotation: ^1.0.6

  syncfusion_flutter_charts: ^20.3.57
  syncfusion_localizations: ^20.3.57
  tuple: ^2.0.1
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^1.0.6

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Alice
      fonts:
        - asset: fonts/Alice-Regular.ttf

  assets:
    - assets/image/open_weather_logo.png
    - assets/image/syncfusion_logo_150dpi.png
    - assets/image/wind_direction_black.png
    - assets/image/wind_direction_white.png
    - assets/weather/
