name: _presentation_layer
description: Presentation Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer
    
  country_picker: ^2.0.15
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  google_mobile_ads: ^1.2.0
  hooks_riverpod: ^2.0.0-dev.7
  intl: ^0.17.0
  logging: ^1.0.2
  qty: ^0.9.2

  syncfusion_flutter_charts: ^20.1.55
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  
  assets:
    - assets/image/brazil-grunge-flag.jpg
    - assets/image/open_weather_logo.png
    - assets/image/syncfusion_logo_150dpi.png
    - assets/image/wind_direction_black.png
    - assets/image/wind_direction_white.png
