name: _presentation_layer
description: Presentation Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer

  country_picker: ^2.0.15
  faker: ^2.0.0

  flutter:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1
  flutter_hooks: ^0.18.4

  flutter_localizations:
    sdk: flutter

  flutter_slidable: ^1.2.1
  flutter_svg: ^1.0.3
  google_mobile_ads: ^1.2.0
  hooks_riverpod: ^2.0.0-dev.7
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.7.0
  qty: ^0.9.2

  syncfusion_flutter_charts: ^20.1.56
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/image/brazil-grunge-flag.jpg
    - assets/image/open_weather_logo.png
    - assets/image/syncfusion_logo_150dpi.png
    - assets/image/wind_direction_black.png
    - assets/image/wind_direction_white.png
    - assets/weather/

flutter_intl:
  enabled: false
  main_locale: en
  arb_dir: lib/src/l10n
  output_dir: lib/src/l10n/generated
  localizely:
    project_id: 942e7477-7f15-4bb1-813f-99e9c6f83a46
