name: _presentation_layer
description: Presentation Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer

  bitsdojo_window: 0.1.2
  country_picker: # ^2.0.15-dev.1
    git:
      url: https://github.com/cc-nogueira/flutter_country_picker.git

  faker: ^2.0.0

  flutter:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1
  flutter_hooks: ^0.18.4

  flutter_localizations:
    sdk: flutter

  flutter_slidable: ^1.3.0
  google_mobile_ads: ^1.2.0
  hooks_riverpod: 2.0.0-dev.9

  intl: ^0.17.0
  latinize: ^0.1.0-nullsafety.0
  logging: ^1.0.2
  meta: ^1.7.0
  qty: ^0.9.2

  syncfusion_flutter_charts: ^20.1.58
  syncfusion_localizations: ^20.1.58
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/image/brazil-grunge-flag.jpg
    - assets/image/open_weather_logo.png
    - assets/image/syncfusion_logo_150dpi.png
    - assets/image/wind_direction_black.png
    - assets/image/wind_direction_white.png
    - assets/weather/
